// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/enem/2019": {
            "get": {
                "description": "Get question",
                "tags": [
                    "ENEM"
                ],
                "summary": "List questions",
                "responses": {}
            }
        },
        "/enem/2020": {
            "get": {
                "description": "Get question",
                "tags": [
                    "ENEM"
                ],
                "summary": "List questions",
                "responses": {}
            }
        },
        "/enem/2021": {
            "get": {
                "description": "Get question",
                "tags": [
                    "ENEM"
                ],
                "summary": "List questions",
                "responses": {}
            }
        },
        "/enem/2022": {
            "get": {
                "description": "Get question",
                "tags": [
                    "ENEM"
                ],
                "summary": "List questions",
                "responses": {}
            }
        },
        "/enem/2023": {
            "get": {
                "description": "Get question",
                "tags": [
                    "ENEM"
                ],
                "summary": "List questions",
                "responses": {}
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "Gollege",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
