basePath: /v1
host: localhost:8080
info:
  contact: {}
  title: Gollege
  version: "1.0"
paths:
  /enem/{year}/{lang}:
    get:
      description: List question from an specific year and language
      parameters:
      - description: Year
        in: path
        name: year
        required: true
        type: string
      - description: Language
        in: path
        name: lang
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: List questions
      tags:
      - ENEM
  /enem/files/{year}/{id}:
    get:
      description: Get file from an specific year and id
      parameters:
      - description: Year
        in: path
        name: year
        required: true
        type: string
      - description: ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - '*/*'
      responses: {}
      summary: Get file
      tags:
      - ENEM
swagger: "2.0"
